name: build-deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Node
      uses: actions/setup-node@master
      with:
        node-version: 18

    - name: Install Dependent Node Pkgs
      run: npm install
    
    - name: Build
      run: chmod +x ./deploy.sh && ./deploy.sh

